### ISSUE TITLE
Add a contributing guide

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Literature#18]
I am assigning @CircleCode since he started this few months ago.

**Comment by osaris** [comment]
Few things we need to address in the contributor guide imo :
* how to use your fork of the lib you are contributing to in your script
* how to run tests for your fork

**Comment by Hywan** [comment]
Ok. We start easy and then ameliorate the guide if needed. Agree?

**Comment by osaris** [comment]
Yes, to start we should focus on users with some skills with git/github and address issue relative to hoa itself (tests etc). It's very frustrating to be motivated to contribute but to be stuck with problems related to the workflow of the project.

**Comment by Hywan** [comment]
A classical workflow is the following:
  * Download Git repository (not from Composer),
  * `composer install`,
  * Edit,
  * Run tests,
  * Create a pull request.

Are you ok?

**Comment by osaris** [comment]
Yes, that's it.
