### ISSUE TITLE
Subtitles and CORS = conflict in some browsers

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/Literature#21]
When you go to the english page of awecode there is no subtitle, not english speaking stuff

**Comment by Hywan** [comment]
With recent versions of some browsers, there is an issue with downloading the subtitles. I am fixing this.

**Comment by Hywan** [comment]
Fixed. It was not an issue with CORS but the URL of the subtitles was incorrect. Fixed by https://github.com/hoaproject/W3/commit/0c8e465d7301e48f8dbc2e6a09a26ac333053e31.

**Comment by Hywan** [comment]
Thanks for the bug report!
